// Package docgen generates the generated-docs artifacts under docs/
// (FLAGS.md, FLAGS.zh-CN.md, PLUGINS.md, PLUGINS.zh-CN.md) from the
// live in-source registries. The artifacts are build products, never
// hand-edited; the guard test in this package fails CI the moment a
// flag/plugin change lands without a `just docs-gen` regeneration —
// and the zh artifacts additionally require every new flag to carry a
// Chinese usage translation (zh.go), so the bilingual pair cannot
// drift apart either.
//
// Package docgen 从源码内的活体 registry 生成 docs/ 下的文档产物
// （FLAGS.md、FLAGS.zh-CN.md、PLUGINS.md、PLUGINS.zh-CN.md）。产物只
// 由生成器写入、绝不手改；本包内的守卫测试在 flag/插件变更后未跑
// `just docs-gen` 时会让 CI 变红——且中文产物额外要求每个新 flag 都
// 带中文 usage 翻译（zh.go），双语对之间同样不可能漂移。
//
// Rationale / 设计动机: the hand-written flag tables in the READMEs
// had drifted three ways at once (28 vs 45 vs 58 flags) against the
// real registry. Generating the tables from the same pflag/plugin
// registries the binary serves at runtime makes drift structurally
// impossible — the doc IS the registry, formatted.
//
// / 动机：README 里手写的 flag 表曾同时漂移出三个口径（28/45/58）。
// 从二进制运行时真正使用的同一份 pflag/插件 registry 生成表格，让
// 漂移在结构上不可能发生——文档就是 registry 本身的排版形态。
package docgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/LCUstinian/FG-QiMen/cmd"
	"github.com/LCUstinian/FG-QiMen/internal/core/credential"
	"github.com/LCUstinian/FG-QiMen/internal/plugins"
	"github.com/spf13/pflag"
)

// flagGroupOrder fixes the section order of the FLAGS artifacts (stable
// output; groups absent from the registry are skipped, unannotated
// flags land in a trailing "Ungrouped" section as a tripwire — the
// flags_test.go guard should make that section stay empty).
//
// / flagGroupOrder 固定 FLAGS 产物的小节顺序（输出稳定）；registry
// 里没有的组跳过，未标注分组的 flag 落到末尾 "Ungrouped" 小节作绊线
// ——flags_test.go 的守卫应保证该小节恒为空。
var flagGroupOrder = []string{
	"Target",
	"Workspace",
	"Ports",
	"Network",
	"Concurrency",
	"Credentials",
	"Output",
	"Schedule",
	"Behavior",
	"Safety",
}

// generatedBanner is stamped at the top of every artifact. All four
// artifacts (en+zh × flags+plugins) are products of the same run.
// / generatedBanner 盖在每个产物顶部。四个产物（中英 × flags/plugins）
// 都是同一次运行的产物。
const generatedBanner = `<!-- GENERATED by ` + "`just docs-gen`" + ` (tools/gendocs) — DO NOT EDIT BY HAND.
     The in-source registries (cmd/flags.go, cmd/multishort.go,
     internal/plugins/adapted) are the single source of truth; this
     file is their build artifact (Chinese version: usage strings
     translated in internal/docgen/zh.go). internal/docgen's guard
     test fails CI when this file drifts from the registries. -->

`

// flagsRender carries the per-language copy for the FLAGS artifact.
// Everything structural (grouping, ordering, cell escaping) is shared;
// only the intro, headers, group names and meaning-column source vary.
//
// / flagsRender 携带 FLAGS 产物的逐语言文案。结构性内容（分组、排序、
// 单元格转义）共享；只有 intro、表头、组名和 Meaning 列来源不同。
type flagsRender struct {
	intro        func(total, groups int) string
	headers      [4]string
	groupDisplay func(string) string
	meaning      func(f *pflag.Flag) string
	twinLink     string // cross-language twin link under the title / 标题下的跨语言孪生链接
}

// enRender / zhRender — the two language variants.
// / enRender / zhRender——两个语言变体。
var (
	enRender = flagsRender{
		intro: func(total, groups int) string {
			return fmt.Sprintf("%d flags in %d groups, rendered from the live flag registry "+
				"(the same set `fg-qimen --help` prints). The tables below are the\n"+
				"authoritative machine-checked reference; add a flag by editing\n"+
				"cmd/flags.go, then run `just docs-gen`.\n\n", total, groups)
		},
		headers:      [4]string{"Short", "Long", "Default", "Meaning"},
		groupDisplay: func(g string) string { return g },
		meaning:      func(f *pflag.Flag) string { return f.Usage },
		twinLink:     "> [中文版本](FLAGS.zh-CN.md)",
	}
	zhRender = flagsRender{
		intro: func(total, groups int) string {
			return fmt.Sprintf("%d 个 flag，分 %d 组，由活体 flag registry 渲染（与 `fg-qimen --help` 输出\n"+
				"同一集合）。下表为机器校验的权威参考；新增 flag 请改 cmd/flags.go\n"+
				"并在 internal/docgen/zh.go 配中文说明，然后跑 `just docs-gen`。\n\n", total, groups)
		},
		headers: [4]string{"短参", "长参", "默认值", "说明"},
		groupDisplay: func(g string) string {
			if zh, ok := groupZh[g]; ok {
				return zh
			}
			return g
		},
		meaning: func(f *pflag.Flag) string {
			if zh, ok := flagDescZh[f.Name]; ok {
				return zh
			}
			return f.Usage // unreachable when ValidateFlagDescZh passes / ValidateFlagDescZh 通过时不可达
		},
		twinLink: "> [English version](FLAGS.md)",
	}
)

// FlagsMarkdown renders the full persistent-flag registry as markdown:
// one section per group, each a Short/Long/Default/Meaning table. The
// 2-letter aliases (-ot/-oj/-oc/-uf/-pf) come from cmd.MultiCharShorts
// so the rendered column matches what the parser actually accepts.
//
// / FlagsMarkdown 把完整的持久化 flag registry 渲染成 markdown：每组
// 一节、节内 Short/Long/Default/Meaning 表格。2 字母别名（-ot/-oj/
// -oc/-uf/-pf）取自 cmd.MultiCharShorts，渲染列与解析器实际接受的
// 形式一致。
func FlagsMarkdown() string { return renderFlags(enRender) }

// FlagsMarkdownZh is the Chinese twin of FlagsMarkdown: group titles
// and the meaning column come from zh.go, everything structural is
// identical so the two artifacts stay row-for-row comparable.
//
// / FlagsMarkdownZh 是 FlagsMarkdown 的中文孪生版：组名与说明列取自
// zh.go，结构性内容完全一致，两个产物逐行可比。
func FlagsMarkdownZh() string { return renderFlags(zhRender) }

// renderFlags is the shared FLAGS-artifact renderer.
// / renderFlags 是共享的 FLAGS 产物渲染器。
func renderFlags(r flagsRender) string {
	fs := cmd.PersistentFlagSet()
	shortToLong := cmd.MultiCharShorts()
	longToShort := make(map[string]string, len(shortToLong))
	for s, l := range shortToLong {
		longToShort[l] = s
	}

	byGroup := map[string][]*pflag.Flag{}
	fs.VisitAll(func(f *pflag.Flag) {
		group := "Ungrouped"
		if a := f.Annotations["group"]; len(a) > 0 && a[0] != "" {
			group = a[0]
		}
		byGroup[group] = append(byGroup[group], f)
	})

	groups := make([]string, 0, len(flagGroupOrder)+1)
	for _, g := range flagGroupOrder {
		if len(byGroup[g]) > 0 {
			groups = append(groups, g)
		}
	}
	if rest := byGroup["Ungrouped"]; len(rest) > 0 {
		groups = append(groups, "Ungrouped")
	}

	total := 0
	for _, groupFlags := range byGroup {
		total += len(groupFlags)
	}

	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString("# CLI flags\n\n")
	if r.twinLink != "" {
		b.WriteString(r.twinLink)
		b.WriteString("\n\n")
	}
	b.WriteString(r.intro(total, len(groups)))

	for _, g := range groups {
		flags := byGroup[g]
		sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
		fmt.Fprintf(&b, "## %s\n\n", r.groupDisplay(g))
		b.WriteString("| " + strings.Join(r.headers[:], " | ") + " |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, f := range flags {
			short := cellShort(f, longToShort)
			fmt.Fprintf(&b, "| %s | `--%s` | %s | %s |\n",
				short, f.Name, cellDefault(f.DefValue), cellText(r.meaning(f)))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// cellShort renders the short-flag column: single-char pflag shorthand
// first, then the 2-letter rewrite alias, else an em dash.
//
// / cellShort 渲染短参列：先单字符 pflag shorthand，再 2 字母重写别
// 名，都没有则用 em dash。
func cellShort(f *pflag.Flag, longToShort map[string]string) string {
	if f.Shorthand != "" {
		return "`-" + f.Shorthand + "`"
	}
	if s, ok := longToShort[f.Name]; ok {
		return "`-" + s + "`"
	}
	return "—"
}

// cellDefault renders the default-value column; empty means "no
// default" (em dash) rather than "defaults to empty string".
//
// / cellDefault 渲染默认值列；空即"无默认值"（em dash），而非"默认
// 空字符串"。
func cellDefault(def string) string {
	if def == "" {
		return "—"
	}
	return "`" + cellText(def) + "`"
}

// cellText flattens a usage string into a single safe table cell:
// newlines collapse to spaces, pipes escape so they can't break the
// markdown table.
//
// / cellText 把 usage 文本压成安全的单行表格单元格：换行折叠为空格，
// 管道符转义以免破坏 markdown 表格。
func cellText(s string) string {
	r := strings.NewReplacer("\r", "", "\n", " ", "|", `\|`)
	return strings.TrimSpace(r.Replace(s))
}

// pluginsRender carries the per-language copy for the PLUGINS artifact.
// / pluginsRender 携带 PLUGINS 产物的逐语言文案。
type pluginsRender struct {
	intro    func(total, identify, credential int) string
	headers  [4]string
	twinLink string
}

// PluginsMarkdown renders the registered plugin registry as markdown:
// name, default ports, and the Identify/Credential capability bits.
// The Identify column reflects the plugin's ModeIdentify bit; the
// Credential column reflects the credential-spray reality — a plugin
// counts as credential-capable when an authenticator with the same
// service name is registered in the credential registry
// (internal/core/credential/auth, wired through the central
// Scheduler), with the plugin's own ModeCredential bit as fallback.
// The authenticator registry is authoritative because most plugins
// leave Credential() as a stub and the Scheduler owns the spray loop.
//
// / PluginsMarkdown 把已注册的插件 registry 渲染成 markdown：名称、
// 默认端口、Identify/Credential 能力位。Identify 列取插件的
// ModeIdentify 位；Credential 列反映凭据喷洒的真实情况——当
// credential registry（internal/core/credential/auth，经中央
// Scheduler 接线）里存在同名 authenticator 时该插件计为支持凭据
// 测试，插件自身的 ModeCredential 位作 fallback。以 authenticator
// registry 为权威：多数插件把 Credential() 留成 stub，喷洒循环由
// Scheduler 负责。
func PluginsMarkdown() string {
	return renderPlugins(pluginsRender{
		intro: func(total, identify, credential int) string {
			return fmt.Sprintf("%d plugins registered from `internal/plugins/adapted` "+
				"(%d with Identify capability, %d with Credential capability), "+
				"rendered from the live registry. Add a plugin by implementing\n"+
				"`plugins.Plugin` under `internal/plugins/adapted/<category>/` —\n"+
				"see docs/PLUGIN_GUIDE.md — then run `just docs-gen`.\n\n",
				total, identify, credential)
		},
		headers:  [4]string{"Plugin", "Default ports", "Identify", "Credential"},
		twinLink: "> [中文版本](PLUGINS.zh-CN.md)",
	})
}

// PluginsMarkdownZh is the Chinese twin of PluginsMarkdown. The table
// body (plugin names, port lists, capability bits) is language-neutral,
// so only the intro and headers differ.
//
// / PluginsMarkdownZh 是 PluginsMarkdown 的中文孪生版。表格本体（插件
// 名、端口列表、能力位）语言无关，只有 intro 与表头不同。
func PluginsMarkdownZh() string {
	return renderPlugins(pluginsRender{
		intro: func(total, identify, credential int) string {
			return fmt.Sprintf("%d 个插件注册自 `internal/plugins/adapted`（%d 个具备 Identify 能力，\n"+
				"%d 个具备 Credential 能力），由活体 registry 渲染。新增插件：在\n"+
				"`internal/plugins/adapted/<category>/` 下实现 `plugins.Plugin`\n"+
				"—— 见 docs/PLUGIN_GUIDE.md —— 然后跑 `just docs-gen`。\n\n",
				total, identify, credential)
		},
		headers:  [4]string{"插件", "默认端口", "识别", "凭据"},
		twinLink: "> [English version](PLUGINS.md)",
	})
}

// renderPlugins is the shared PLUGINS-artifact renderer.
// / renderPlugins 是共享的 PLUGINS 产物渲染器。
func renderPlugins(r pluginsRender) string {
	all := plugins.All()
	credNames := map[string]bool{}
	for _, n := range credential.Authenticators() {
		credNames[n] = true
	}

	identify := 0
	credential := 0
	for _, p := range all {
		m := p.Modes()
		if m&plugins.ModeIdentify != 0 {
			identify++
		}
		if m&plugins.ModeCredential != 0 || credNames[p.Name()] {
			credential++
		}
	}

	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString("# Plugins\n\n")
	if r.twinLink != "" {
		b.WriteString(r.twinLink)
		b.WriteString("\n\n")
	}
	b.WriteString(r.intro(len(all), identify, credential))

	b.WriteString("| " + strings.Join(r.headers[:], " | ") + " |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, p := range all {
		m := p.Modes()
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			p.Name(), cellPorts(p.Ports()), cellBit(m, plugins.ModeIdentify),
			cellBool(credNames[p.Name()] || m&plugins.ModeCredential != 0))
	}
	return b.String()
}

// cellPorts renders a sorted, comma-joined port list.
// / cellPorts 渲染排序后逗号连接的端口列表。
func cellPorts(ports []int) string {
	sorted := make([]int, len(ports))
	copy(sorted, ports)
	sort.Ints(sorted)
	parts := make([]string, 0, len(sorted))
	for _, p := range sorted {
		parts = append(parts, fmt.Sprintf("%d", p))
	}
	return strings.Join(parts, ", ")
}

// cellBit renders a Mode capability bit as a check mark or a dash.
// / cellBit 把 Mode 能力位渲染成对勾或短横。
func cellBit(m, bit plugins.Mode) string {
	return cellBool(m&bit != 0)
}

// cellBool renders a capability as a check mark or a dash.
// / cellBool 把能力渲染成对勾或短横。
func cellBool(ok bool) string {
	if ok {
		return "✅"
	}
	return "–"
}
